#!/usr/bin/ruby
=begin rdoc
* System     : rummage
* Author     : Xanthalas
* Description: Top level test file which calls all other tests.

 -----------: Change Log ----------------------------------------------------
 Date       : October 2009                             Author: Xanthalas
            : Initial version

=end
require 'test/unit'
require 'searchTest'
require 'matchTest'

